server:
  port: 8082
  max-http-request-header-size: 128KB
spring:
  application:
    name: common
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
