server:
  port: 8081
spring:
  application:
    name: service-request
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
service:
  common:
    url: http://localhost:8082
